---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: automation-hub-token
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: automation-hub-token
  dataFrom:
  - extract:
      key: {{ .Values.agof.automationHubTokenKey }}
